### ISSUE TITLE
Enter Password option is not supported

### ISSUE THREAD

**Issue by icyKira** [EddyVerbruggen/cordova-plugin-touchid#2]
Having "Enter Password" as an option on Touch ID popup that doesn't do anything is making this plugin almost useless in production environment. Is there any chance for this option to be implemented?

Thanks!!

**Comment by si458** [comment]
please try my repo - https://github.com/HestorLtd/com.hestor.touchid

**Comment by EddyVerbruggen** [comment]
Hi @si458 does this authenticate the user with his iOS passcode (the thing attached to your fingerprint), or did you build a custom password dialog? FYI - I was planning on implementing something which uses the actual passcode.

**Comment by si458** [comment]
Hi @EddyVerbruggen 
my plugin simple passes a set password from your html for the Enter Password stage
ive looked at the documents for iOS and it appears the enter password is ment to be set within your app and not the passcode assigned with TouchID
so in theory you could implement a passcode instead of a password, i will look into this and change my plugin for password or passcode :)

**Comment by EddyVerbruggen** [comment]
@si458 I have a working prototype based on passcode which I will check in later today. I'd love you to check it out.

**Comment by EddyVerbruggen** [comment]
@icyKira and @si458 please see the updated docs and give v 2.0.0 a try.

Thx,
Eddy

**Comment by si458** [comment]
Hi,
brilliant update, works ok,
im going to edit my repo and include the passcode as another option to give the user choices of things
however, if I select passcode instead of fingerprint then say enter passcode wrong 5 times it locks me out
then if i select use my fingerprint again, i just keep getting a window saying authentication disabled for 1 min and im not able to use my finger :(
any way around this?
Simon

**Comment by EddyVerbruggen** [comment]
Hi,

Thanks for testing this so quickly!

And no, that's how Apple designed it and it works the same as when you type in your passcode incorrectly when unlocking your device.

**Comment by si458** [comment]
Hi,
this is going to be a pain in the bum, because more testing...
get passcode wrong 5 times, locks me out, wait 1 min, then try again, it always asks for passcode instead of using fingerprint
you have to then get the passcode correct before you can use your fingerprint again, strange???
Simon

**Comment by EddyVerbruggen** [comment]
That's how Apple designed it and I'm sure they had good reasons and a lot of advise of (external) security consultants.
